version: '3.1'
services:
  frontend:
    build: .
    volumes:
      - /node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - backend

networks:
  backend: